# Generated by Django 4.1.3 on 2023-03-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='res_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tier',
            name='res_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tier',
            name='res_3',
            field=models.IntegerField(default=0),
        ),
    ]
